site_name: Felipe Bravo-Marquez
theme: mkdocs  
repo_url: https://felipebravom.com
site_description: Personal Webpage of Felipe Bravo-Marquez
nav:
    - Home: index.md
    - Publications: publications.md
    - CV: cv.md
    - Teaching: 
        - 'Natural Language Processing': 'https://github.com/dccuchile/CC6205/'
        - 'Data Mining/Data Science/Machine Learning (in Spanish)': 'teaching/data.md'

