site_name: Felipe Bravo-Marquez
theme: mkdocs  
repo_url: https://felipebravom.com
site_description: Personal Webpage of Felipe Bravo-Marquez
nav:
    - Home: index.md
    - Publications: publications.md
    - Bio: bio.md      
    - CV: 
        - 'Web Format': cv.md
        - 'PDF': 'documents/cv_full.pdf'
    - Teaching: 
        - 'Natural Language Processing': 'https://github.com/dccuchile/CC6205/'
        - 'Data Mining': 'https://github.com/dccuchile/CC5206/'
        - 'Statistical Thinking': 'https://github.com/dccuchile/CC6104'
        - 'Misc (in Spanish)': 'teaching/data.md'          
          

