site_name: Felipe Bravo-Marquez
theme: mkdocs  
repo_url: https://cs.waikato.ac.nz/~fbravoma
site_description: Personal Webpage of Felipe Bravo-Marquez
nav:
    - Home: index.md
    - Publications: publications.md
    - CV: cv.md
    - Slides: 
        - 'Natural Language Processing': 'teaching/nlp.md'
        - 'Data Analysis in R (in Spanish)': 'teaching/data_anal.md'
        - 'Web Information Retrieval (in Spanish)': 'teaching/webir.md'

